version: "3.7"
services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
  db:
    image: postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=db-wrz2z
    expose:
      - 5432
secrets:
  db-password:
    file: db/password.txt
